/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.finalproject.ui;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Administrator
 */
public class AccountantJPanel extends javax.swing.JPanel {
    MainJFrame jFrame;

    /**
     * Creates new form operationsPanel
     */
    public AccountantJPanel(MainJFrame jFrame) {
        initComponents();

        this.jFrame = jFrame;
        RefundJPanel refundJPanel = new RefundJPanel(jFrame);
        StatementJPanel statementJPanel = new StatementJPanel(jFrame);

        jTabbedPane.addTab("RefundOrder", refundJPanel);
        jTabbedPane.addTab("Statement", statementJPanel);
        refundJPanel.displayRefundOrder();
        refundJPanel.displayRefundOrderList();
        statementJPanel.displayStatement();
        statementJPanel.displayStatementList();

        jTabbedPane.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                int index = jTabbedPane.getSelectedIndex();
                switch (index) {
                    case 0:
                        refundJPanel.displayRefundOrder();
                        refundJPanel.displayRefundOrderList();
                        break;
                    case 1:
                        statementJPanel.displayStatement();
                        statementJPanel.displayStatementList();
                        break;
                    default:
                        throw new AssertionError();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables
}
