/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.finalproject.ui;

import com.finalproject.model.BusinessOrder;
import com.finalproject.model.BusinessOrderStatusType;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Administrator
 */
public class DataJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DataJPanel
     */
    public DataJPanel() {
        initComponents();
        displayMonthlyOrderData();
        displayOrderStatusData();
    }

    public void displayMonthlyOrderData() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset( );

        int[] amounts = new int[12];
        for (BusinessOrder order: BusinessOrder.find("Digital Platform")) {
            amounts[order.getCreateDate().getMonthValue()] += order.getTotalAmount() / 100;
        }
        for (int i = 0; i < amounts.length; i++) {
            dataset.addValue(amounts[i], "order", String.valueOf(i));
        }
        JFreeChart lineChart = ChartFactory.createLineChart("Monthly Order", "Months", "Amount", dataset);
        ChartPanel chartPanel = new ChartPanel(lineChart);
        leftjPanel.removeAll();
        leftjPanel.add(chartPanel);
        leftjPanel.validate();
    }

    public void displayOrderStatusData() {
        DefaultPieDataset dataset = new DefaultPieDataset<>( );

        int[] types = new int[BusinessOrderStatusType.values().length];
        for (BusinessOrder order: BusinessOrder.find("Digital Platform")) {
            types[order.getOrderStatusType().ordinal()] += order.getTotalAmount() / 100;
        }
        for (int i = 0; i < types.length; i++) {
            dataset.setValue(BusinessOrderStatusType.values()[i], types[i]);
        }
        JFreeChart lineChart = ChartFactory.createPieChart("Order status", dataset);
        ChartPanel chartPanel = new ChartPanel(lineChart);
        rightjPanel.removeAll();
        rightjPanel.add(chartPanel);
        rightjPanel.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        leftjPanel = new javax.swing.JPanel();
        rightjPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(242, 237, 231));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Data");

        jSplitPane1.setDividerLocation(400);

        leftjPanel.setPreferredSize(new java.awt.Dimension(400, 507));
        leftjPanel.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setLeftComponent(leftjPanel);

        rightjPanel.setPreferredSize(new java.awt.Dimension(400, 507));
        rightjPanel.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(rightjPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(374, 374, 374)
                .addComponent(jLabel1)
                .addContainerGap(388, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel leftjPanel;
    private javax.swing.JPanel rightjPanel;
    // End of variables declaration//GEN-END:variables
}
