/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.finalproject.ui;

import com.finalproject.model.Role;
import com.finalproject.model.User;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Administrator
 */
public class InfoJPanel extends javax.swing.JPanel {
    MainJFrame jFrame;

    /**
     * Creates new form InfoJPanel
     */
    public InfoJPanel(MainJFrame jFrame) {
        initComponents();
        this.jFrame = jFrame;
        logoutjButton.setEnabled(false);
        
        ImageIcon i = new ImageIcon("src/main/resources/image/Logout.png");
        int width = 50, height = 50;
        Image image = i.getImage();
        Image smallImage = image.getScaledInstance(width, height, Image.SCALE_FAST);
        ImageIcon smallIcon = new ImageIcon(smallImage);
        cartjLabel.setIcon(smallIcon);
    }

    public void displayUser() {
        User user = jFrame.getUser();
        Role role = jFrame.getRole();

        if (user != null || role != null) {
            logoutjButton.setEnabled(true);
        }

        if (user == null) {
            usernamejTextField.setText("");
        } else {
            usernamejTextField.setText(user.getUsername());
        }

        if (role == null) {
            rolejTextField.setText("");
            organizationjTextField.setText("");
            enterprisejTextField.setText("");
        } else {
            rolejTextField.setText(role.toString());
            organizationjTextField.setText(role.getOrganization().toString());
            enterprisejTextField.setText(role.getOrganization().getEnterprise().toString());
        }

        if (user == null && role == null) {
            logoutjButton.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernamejLabel = new javax.swing.JLabel();
        usernamejTextField = new javax.swing.JTextField();
        organizationjLabel = new javax.swing.JLabel();
        organizationjTextField = new javax.swing.JTextField();
        rolejLabel = new javax.swing.JLabel();
        rolejTextField = new javax.swing.JTextField();
        enterprisejLabel = new javax.swing.JLabel();
        enterprisejTextField = new javax.swing.JTextField();
        logoutjButton = new javax.swing.JButton();
        cartjLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(104, 173, 226));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(100, 600));

        usernamejLabel.setFont(new java.awt.Font("Chalkboard SE", 0, 14)); // NOI18N
        usernamejLabel.setText("Username");

        usernamejTextField.setEnabled(false);

        organizationjLabel.setFont(new java.awt.Font("Chalkboard SE", 0, 14)); // NOI18N
        organizationjLabel.setText("Organization");

        organizationjTextField.setEnabled(false);

        rolejLabel.setFont(new java.awt.Font("Chalkboard SE", 0, 14)); // NOI18N
        rolejLabel.setText("Role");

        rolejTextField.setEnabled(false);

        enterprisejLabel.setFont(new java.awt.Font("Chalkboard SE", 0, 14)); // NOI18N
        enterprisejLabel.setText("Enterprise");

        enterprisejTextField.setEnabled(false);

        logoutjButton.setFont(new java.awt.Font("Chalkboard SE", 0, 14)); // NOI18N
        logoutjButton.setText("LOG OUT");
        logoutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(cartjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutjButton)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterprisejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(organizationjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rolejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rolejLabel)
                    .addComponent(usernamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernamejLabel)
                    .addComponent(organizationjLabel)
                    .addComponent(enterprisejLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(usernamejLabel)
                .addGap(18, 18, 18)
                .addComponent(usernamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rolejLabel)
                .addGap(18, 18, 18)
                .addComponent(rolejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(organizationjLabel)
                .addGap(18, 18, 18)
                .addComponent(organizationjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enterprisejLabel)
                .addGap(18, 18, 18)
                .addComponent(enterprisejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cartjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutjButton))
                .addContainerGap(142, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutjButtonActionPerformed
        // TODO add your handling code here:
        jFrame.setUser(null);
        jFrame.setRole(null);
        displayUser();
        jFrame.getjSplitPane().setRightComponent(new LoginJPanel(jFrame));
        logoutjButton.setEnabled(false);
    }//GEN-LAST:event_logoutjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cartjLabel;
    private javax.swing.JLabel enterprisejLabel;
    private javax.swing.JTextField enterprisejTextField;
    private javax.swing.JButton logoutjButton;
    private javax.swing.JLabel organizationjLabel;
    private javax.swing.JTextField organizationjTextField;
    private javax.swing.JLabel rolejLabel;
    private javax.swing.JTextField rolejTextField;
    private javax.swing.JLabel usernamejLabel;
    private javax.swing.JTextField usernamejTextField;
    // End of variables declaration//GEN-END:variables
}
