/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.finalproject.ui;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Administrator
 */
public class QualityManagerJPanel extends javax.swing.JPanel {
    MainJFrame jFrame;

    /**
     * Creates new form operationsPanel
     */
    public QualityManagerJPanel(MainJFrame jFrame) {
        initComponents();

        this.jFrame = jFrame;
        PurchaseOrderJPanel purchaseOrderJPanel = new PurchaseOrderJPanel(jFrame);
        ProductJPanel productJPanel = new ProductJPanel(jFrame);

        jTabbedPane.addTab("Product", productJPanel);
        jTabbedPane.addTab("PurchaseOrder", purchaseOrderJPanel);
        purchaseOrderJPanel.displayOrder();
        purchaseOrderJPanel.displayOrderList();
        productJPanel.displayProduct();
        productJPanel.displayProductList();

        jTabbedPane.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                int index = jTabbedPane.getSelectedIndex();
                switch (index) {
                    case 0:
                        productJPanel.displayProduct();
                        productJPanel.displayProductList();
                        break;
                    case 1:
                        purchaseOrderJPanel.displayOrder();
                        purchaseOrderJPanel.displayOrderList();
                        break;
                    default:
                        throw new AssertionError();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables
}
