/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.finalproject.ui;

import com.finalproject.model.BusinessDeliverOrder;
import com.finalproject.model.BusinessDeliverOrderStatusType;
import com.finalproject.model.BusinessOrder;
import com.finalproject.model.BusinessOrderStatusType;
import com.finalproject.model.BusinessVehicle;
import com.finalproject.model.BusinessWarehouse;
import com.finalproject.model.BusinessWarehouseEntry;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class ShippmentJFrame extends javax.swing.JFrame {
    MainJFrame jFrame;
    BusinessOrder order;
    /**
     * Creates new form ShippmentJFrame
     */
    public ShippmentJFrame(MainJFrame jFrame, BusinessOrder order) {
        initComponents();
        setTitle("Select warehouse and vehicle");
        this.jFrame = jFrame;
        this.order = order;
        warehousejComboBox.removeAllItems();
        for (BusinessWarehouse ts: BusinessWarehouse.find(BusinessWarehouse.class)) {
            warehousejComboBox.addItem(ts);
        }
        vehiclejComboBox.removeAllItems();
        for (BusinessVehicle ts: BusinessVehicle.findAvailableVehicle()) {
            vehiclejComboBox.addItem(ts);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        warehousejLabel = new javax.swing.JLabel();
        warehousejComboBox = new javax.swing.JComboBox<>();
        vehiclejLabel = new javax.swing.JLabel();
        vehiclejComboBox = new javax.swing.JComboBox<>();
        finishjButton = new javax.swing.JButton();
        tolocationjLabel = new javax.swing.JLabel();
        toLocationjTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(242, 237, 231));

        warehousejLabel.setFont(new java.awt.Font("Chalkboard SE", 0, 14)); // NOI18N
        warehousejLabel.setText("Warehouse");

        warehousejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warehousejComboBoxActionPerformed(evt);
            }
        });

        vehiclejLabel.setFont(new java.awt.Font("Chalkboard SE", 0, 14)); // NOI18N
        vehiclejLabel.setText("Vehicle");

        finishjButton.setFont(new java.awt.Font("Chalkboard SE", 0, 14)); // NOI18N
        finishjButton.setText("Start");
        finishjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishjButtonActionPerformed(evt);
            }
        });

        tolocationjLabel.setFont(new java.awt.Font("Chalkboard SE", 0, 14)); // NOI18N
        tolocationjLabel.setText("To Location");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(warehousejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(warehousejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(vehiclejLabel)
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(tolocationjLabel)
                                .addGap(50, 50, 50)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vehiclejComboBox, 0, 92, Short.MAX_VALUE)
                            .addComponent(toLocationjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(finishjButton)
                .addGap(156, 156, 156))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(warehousejLabel)
                    .addComponent(warehousejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehiclejLabel)
                    .addComponent(vehiclejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tolocationjLabel)
                    .addComponent(toLocationjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(finishjButton)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void warehousejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warehousejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warehousejComboBoxActionPerformed

    private void finishjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishjButtonActionPerformed
        // TODO add your handling code here:
        try {
            BusinessWarehouseEntry entry = new BusinessWarehouseEntry();
            entry.setProduct(order.getProduct());
            entry.setBusinessWarehouse((BusinessWarehouse)warehousejComboBox.getSelectedItem());
            entry.setQuantity(-order.getQuantity());
            entry.save();

            BusinessDeliverOrder deliverOrder = new BusinessDeliverOrder();
            deliverOrder.setBusinessProduct(order.getProduct());
            deliverOrder.setBusinessVehicle((BusinessVehicle)vehiclejComboBox.getSelectedItem());
            deliverOrder.setFromEnterprise(jFrame.getRole().getOrganization().getEnterprise());
            deliverOrder.setOrderStatusType(BusinessDeliverOrderStatusType.CREATE);
            deliverOrder.setFee((int)(order.getTotalAmount() * 0.1));
            deliverOrder.setFromLocation(entry.getBusinessWarehouse().getLocation());
            deliverOrder.setToLocation(toLocationjTextField.getText());
            deliverOrder.save();

            order.setOrderStatusType(BusinessOrderStatusType.SHIPPING);
            order.flush();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Shippment error: " + e.getMessage());
            return;
        }
        JOptionPane.showMessageDialog(this, "Shippment start");
        setVisible(false);
    }//GEN-LAST:event_finishjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton finishjButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField toLocationjTextField;
    private javax.swing.JLabel tolocationjLabel;
    private javax.swing.JComboBox<BusinessVehicle> vehiclejComboBox;
    private javax.swing.JLabel vehiclejLabel;
    private javax.swing.JComboBox<BusinessWarehouse> warehousejComboBox;
    private javax.swing.JLabel warehousejLabel;
    // End of variables declaration//GEN-END:variables
}
