/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.finalproject.ui;

import com.finalproject.model.BusinessWarehouse;
import com.finalproject.model.PermissionType;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class WarehouseJPanel extends javax.swing.JPanel {
    MainJFrame jFrame;
    BusinessWarehouse warehouse;
    /**
     * Creates new form orderJPanel
     */
    public WarehouseJPanel(MainJFrame jFrame) {
        initComponents();
        this.jFrame = jFrame;

        String className = "Warehouse";
        if (!jFrame.getUser().hasPermission(className, PermissionType.EDIT)) {
            warehouseModifyjButton.setEnabled(false);
        }
        if (!jFrame.getUser().hasPermission(className, PermissionType.CREATE)) {
            warehouseCreatejButton.setEnabled(false);
        }
        if (!jFrame.getUser().hasPermission(className, PermissionType.VIEW)) {
            warehousejButton.setEnabled(false);
        }
        if (!jFrame.getUser().hasPermission(className, PermissionType.DELETE)) {
            warehouseDeletejButton.setEnabled(false);
        }
    }

    public final void displayWarehouse() {
        if (warehouse == null) {
		    createDatePicker.clear();
		    updateDatePicker.clear();
            locationjTextField.setText("");
            availableQuantityjTextField.setText("");
            totalQuantityjTextField.setText("");
        } else {
            warehouse.refresh();
            createDatePicker.setDateTimeStrict(warehouse.getCreateDate());
            updateDatePicker.setDateTimeStrict(warehouse.getUpdateDate());
            locationjTextField.setText(warehouse.getLocation());
            availableQuantityjTextField.setText(String.valueOf(warehouse.getAvailableQuantity()));
            totalQuantityjTextField.setText(String.valueOf(warehouse.getTotalQuantity()));
        }
    }
    
    public final void displayWarehouseList() {
        DefaultTableModel model = (DefaultTableModel) productjTable.getModel();
        model.setRowCount(0);
        
        for (BusinessWarehouse current: BusinessWarehouse.find(BusinessWarehouse.class)) {
            Object[] row = new Object[6];
            row[0] = current.getId();
            row[1] = current.getLocation();
            row[2] = current.getCreateDate();
            row[3] = current.getUpdateDate();
            row[4] = current.getAvailableQuantity();
            row[5] = current.getTotalQuantity();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonjPanel2 = new javax.swing.JPanel();
        warehouseModifyjButton = new javax.swing.JButton();
        warehouseDeletejButton = new javax.swing.JButton();
        warehouseCreatejButton = new javax.swing.JButton();
        warehousejButton = new javax.swing.JButton();
        createDatePicker = new com.github.lgooddatepicker.components.DateTimePicker();
        passwordjLabel1 = new javax.swing.JLabel();
        updateDatePicker = new com.github.lgooddatepicker.components.DateTimePicker();
        passwordjLabel = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        productjTable = new javax.swing.JTable();
        locationjLabel = new javax.swing.JLabel();
        locationjTextField = new javax.swing.JTextField();
        availableQuantityjLabel = new javax.swing.JLabel();
        availableQuantityjTextField = new javax.swing.JTextField();
        totalQuantityjLabel = new javax.swing.JLabel();
        totalQuantityjTextField = new javax.swing.JTextField();

        warehouseModifyjButton.setText("modify");
        warehouseModifyjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warehouseModifyjButtonActionPerformed(evt);
            }
        });

        warehouseDeletejButton.setText("delete");
        warehouseDeletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warehouseDeletejButtonActionPerformed(evt);
            }
        });

        warehouseCreatejButton.setText("create");
        warehouseCreatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warehouseCreatejButtonActionPerformed(evt);
            }
        });

        warehousejButton.setText("view");
        warehousejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warehousejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonjPanel2Layout = new javax.swing.GroupLayout(buttonjPanel2);
        buttonjPanel2.setLayout(buttonjPanel2Layout);
        buttonjPanel2Layout.setHorizontalGroup(
            buttonjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonjPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(warehouseModifyjButton, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(warehousejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(warehouseCreatejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(warehouseDeletejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        buttonjPanel2Layout.setVerticalGroup(
            buttonjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonjPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(warehouseModifyjButton)
                .addGap(18, 18, 18)
                .addComponent(warehouseDeletejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(warehouseCreatejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(warehousejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        createDatePicker.setEnabled(false);

        passwordjLabel1.setText("update_date");

        updateDatePicker.setEnabled(false);

        passwordjLabel.setText("create_date");

        productjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "location", "create_date", "update_date", "available quantity", "total quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane11.setViewportView(productjTable);

        locationjLabel.setText("location");

        availableQuantityjLabel.setText("available quantity");

        totalQuantityjLabel.setText("total quantity");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordjLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordjLabel)
                                    .addComponent(locationjLabel)
                                    .addComponent(availableQuantityjLabel)
                                    .addComponent(totalQuantityjLabel))
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalQuantityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(createDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(availableQuantityjTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                        .addComponent(locationjTextField, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(buttonjPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(locationjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(locationjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordjLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(availableQuantityjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(availableQuantityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalQuantityjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalQuantityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(buttonjPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void warehouseModifyjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warehouseModifyjButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = productjTable.getSelectedRow();

        if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) productjTable.getModel();
        int id = (Integer) model.getValueAt(selectedIndex, 0);
        warehouse = BusinessWarehouse.findById(BusinessWarehouse.class, id);

        try {
            warehouse.setCreateDate(createDatePicker.getDateTimeStrict());
            warehouse.setUpdateDate(updateDatePicker.getDateTimeStrict());
            warehouse.setLocation(locationjTextField.getText());
            warehouse.setAvailableQuantity(Integer.parseInt(availableQuantityjTextField.getText()));
            warehouse.setTotalQuantity(Integer.parseInt(totalQuantityjTextField.getText()));

            warehouse.flush();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Modify error: " + e.toString());
            return;
        }
        JOptionPane.showMessageDialog(this, "Modify done");
        warehouse = null;
        displayWarehouse();
        displayWarehouseList();
    }//GEN-LAST:event_warehouseModifyjButtonActionPerformed

    private void warehouseDeletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warehouseDeletejButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = productjTable.getSelectedRow();

        if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) productjTable.getModel();
        int id = (Integer) model.getValueAt(selectedIndex, 0);
        warehouse = BusinessWarehouse.findById(BusinessWarehouse.class, id);
        warehouse.delete();
        model.removeRow(selectedIndex);
        warehouse = null;
        displayWarehouse();
        displayWarehouseList();
    }//GEN-LAST:event_warehouseDeletejButtonActionPerformed

    private void warehouseCreatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warehouseCreatejButtonActionPerformed
        // TODO add your handling code here:
        BusinessWarehouse bp = new BusinessWarehouse();
        try {
            bp.setCreateDate(createDatePicker.getDateTimeStrict());
            bp.setUpdateDate(updateDatePicker.getDateTimeStrict());
            bp.setLocation(locationjTextField.getText());
            bp.setAvailableQuantity(Integer.parseInt(availableQuantityjTextField.getText()));
            bp.setTotalQuantity(Integer.parseInt(totalQuantityjTextField.getText()));
            bp.save();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Save error: " + e.toString());
            return;
        }
        JOptionPane.showMessageDialog(this, "Save done");
        bp = null;
        displayWarehouse();
        warehouse = bp;
        displayWarehouseList();
    }//GEN-LAST:event_warehouseCreatejButtonActionPerformed

    private void warehousejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warehousejButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = productjTable.getSelectedRow();

        if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) productjTable.getModel();
        int id = (Integer) model.getValueAt(selectedIndex, 0);
        warehouse = BusinessWarehouse.findById(BusinessWarehouse.class, id);
        displayWarehouse();
    }//GEN-LAST:event_warehousejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availableQuantityjLabel;
    private javax.swing.JTextField availableQuantityjTextField;
    private javax.swing.JPanel buttonjPanel2;
    private com.github.lgooddatepicker.components.DateTimePicker createDatePicker;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JLabel locationjLabel;
    private javax.swing.JTextField locationjTextField;
    private javax.swing.JLabel passwordjLabel;
    private javax.swing.JLabel passwordjLabel1;
    private javax.swing.JTable productjTable;
    private javax.swing.JLabel totalQuantityjLabel;
    private javax.swing.JTextField totalQuantityjTextField;
    private com.github.lgooddatepicker.components.DateTimePicker updateDatePicker;
    private javax.swing.JButton warehouseCreatejButton;
    private javax.swing.JButton warehouseDeletejButton;
    private javax.swing.JButton warehouseModifyjButton;
    private javax.swing.JButton warehousejButton;
    // End of variables declaration//GEN-END:variables
}
